In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
mnist = keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()

Using TensorFlow backend.

Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
11493376/11490434 [==============================] - 92s 8us/step

In [2]:
raw_data = pd.read_csv('C:\\Users\\jaya\\Desktop\\New folder (4)\\train.csv')
test_data = pd.read_csv('C:\\Users\\jaya\\Desktop\\New folder (4)\\test.csv')
test_data = np.array(test_data)
labels = raw_data.iloc[:,0:1].values
num = raw_data.iloc[:,0:1].values
pixel_values = raw_data.iloc[:,1:785].values
pixel_values = pixel_values.reshape(pixel_values.shape[0],28,28)
pixel_values = keras.utils.normalize(pixel_values, axis = 1)

In [3]:
test_data = test_data.reshape(test_data.shape[0],28,28)
test_data = keras.utils.normalize(test_data, axis = 1)
labels = keras.utils.to_categorical(labels, num_classes = 10)

In [4]:
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.layers import Convolution2D

In [5]:
model = Sequential()
model.add(Flatten())
model.add(Dense(100,kernel_initializer='uniform',activation='sigmoid',input_dim = 784))

In [6]:
model.add(Dense(100,activation='sigmoid',kernel_initializer='uniform'))
model.add(Dense(100,activation='sigmoid',kernel_initializer='uniform'))
model.add(Dense(10,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics=['accuracy'])
model.fit(pixel_values, labels,epochs=25,batch_size=50)
label_pred = model.predict(test_data)

WARNING:tensorflow:From C:\Users\jaya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\jaya\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/25
42000/42000 [==============================] - 9s 216us/step - loss: 1.0883 - acc: 0.6411
Epoch 2/25
42000/42000 [==============================] - 5s 107us/step - loss: 0.3440 - acc: 0.9022
Epoch 3/25
42000/42000 [==============================] - 4s 107us/step - loss: 0.2526 - acc: 0.9257
Epoch 4/25
42000/42000 [==============================] - 4s 106us/step - loss: 0.1989 - acc: 0.9414
Epoch 5/25
42000/42000 [==============================] - 4s 105us/step - loss: 0.1615 - acc: 0.9512
Epoch 6/25
42000/42000 [==============================] - 4s 107us/step - loss: 0.1347 - acc: 0.9601
Epoch 7/25
42000/42000 [==============================] - 5s 110us/step - loss: 0.1145 - acc: 0.9665
Epoch 8/25
42000/42000 [==============================] - 5s 112us/step - loss: 0.0993 - acc: 0.9711
Epoch 9/25
42000/42000 [==============================] - 5s 115us/step - loss: 0.0866 - acc: 0.9748
Epoch 10/25
42000/42000 [==============================] - 5s 117us/step - loss: 0.0748 - acc: 0.9785
Epoch 11/25
42000/42000 [==============================] - 4s 106us/step - loss: 0.0674 - acc: 0.9803
Epoch 12/25
42000/42000 [==============================] - 5s 110us/step - loss: 0.0572 - acc: 0.9837
Epoch 13/25
42000/42000 [==============================] - 4s 107us/step - loss: 0.0527 - acc: 0.9846
Epoch 14/25
42000/42000 [==============================] - 4s 106us/step - loss: 0.0460 - acc: 0.9875
Epoch 15/25
42000/42000 [==============================] - 5s 117us/step - loss: 0.0396 - acc: 0.9887
Epoch 16/25
42000/42000 [==============================] - 5s 117us/step - loss: 0.0359 - acc: 0.9898
Epoch 17/25
42000/42000 [==============================] - 4s 104us/step - loss: 0.0321 - acc: 0.9914
Epoch 18/25
42000/42000 [==============================] - 5s 120us/step - loss: 0.0277 - acc: 0.9926
Epoch 19/25
42000/42000 [==============================] - 5s 109us/step - loss: 0.0240 - acc: 0.9936
Epoch 20/25
42000/42000 [==============================] - 4s 107us/step - loss: 0.0208 - acc: 0.9945
Epoch 21/25
42000/42000 [==============================] - 4s 106us/step - loss: 0.0192 - acc: 0.9948
Epoch 22/25
42000/42000 [==============================] - 4s 104us/step - loss: 0.0155 - acc: 0.9963
Epoch 23/25
42000/42000 [==============================] - 4s 104us/step - loss: 0.0148 - acc: 0.9961
Epoch 24/25
42000/42000 [==============================] - 4s 104us/step - loss: 0.0133 - acc: 0.9966
Epoch 25/25
42000/42000 [==============================] - 4s 105us/step - loss: 0.0109 - acc: 0.9973

In [7]:
final = []
label_pred = np.array(label_pred)
for p in range(len(label_pred)):
    final.append(label_pred[p].tolist().index(max(label_pred[p])))

In [8]:
final = pd.Series(final)
imageId = pd.Series([x for x in range(1,28001)])

In [9]:
result = pd.concat([imageId, final], axis =1, names = ['ImageId', 'Label'])
result.to_csv('submission.csv', index=False )

In [10]:
result

           0  1
0          1  2
1          2  0
2          3  9
3          4  9
4          5  3
5          6  7
6          7  0
7          8  3
8          9  0
9         10  3
10        11  5
11        12  7
12        13  9
13        14  0
14        15  4
15        16  3
16        17  3
17        18  1
18        19  9
19        20  0
20        21  9
21        22  1
22        23  1
23        24  5
24        25  7
25        26  4
26        27  2
27        28  7
28        29  4
29        30  7
...      ... ..
27970  27971  5
27971  27972  0
27972  27973  4
27973  27974  8
27974  27975  0
27975  27976  3
27976  27977  6
27977  27978  0
27978  27979  1
27979  27980  9
27980  27981  3
27981  27982  1
27982  27983  1
27983  27984  0
27984  27985  4
27985  27986  3
27986  27987  2
27987  27988  2
27988  27989  9
27989  27990  6
27990  27991  7
27991  27992  6
27992  27993  1
27993  27994  9
27994  27995  7
27995  27996  9
27996  27997  7
27997  27998  3
27998  27999  9
27999  28000  2

[28000 rows x 2 columns]